### ISSUE TITLE
Bad links from no ZUID

### ISSUE THREAD

**Issue by ardeay** [zesty-io/explorer#4]
When loading via CDNJS we dont have the Instance ZUID 
![image](https://user-images.githubusercontent.com/729972/162815381-2971b28f-c765-4fe3-8aa6-becb0b80224f.png)

If this data is missing ( when not implemted from react loading {content}) it can be accessed off the response object in `res.headers.z-zuid`
![image](https://user-images.githubusercontent.com/729972/162819014-e2a07c9d-281a-4701-9d78-b89f39597255.png)

**Comment by darwin808** [comment]
<script
      type="text/javascript"
      src="https://cdn.jsdelivr.net/gh/zesty-io/explorer@cdn/dist/explorer.production.min11.js"
      defer="defer"
    ></script>
    
    @ardeay you can check in this link the cdn cache older versions
