### ISSUE TITLE
constants reference is breaking explorer via React 

### ISSUE THREAD

**Issue by ardeay** [zesty-io/explorer#7]
![image](https://user-images.githubusercontent.com/729972/163013360-03a8597c-57b8-4875-b88e-7a942c52c2db.png)

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/163030385-46110e2b-adfc-482c-8157-0269ebc20131.png)
![image](https://user-images.githubusercontent.com/71545960/163030421-cb72c60e-9355-4c4b-ae06-4cd439286b8c.png)
![image](https://user-images.githubusercontent.com/71545960/163030527-c8f33f55-1148-4bab-9e05-a9a6367c1d3e.png)
